# Generated by Django 3.2.9 on 2021-11-12 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Casts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cast_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Cast',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Categorie',
                'ordering': ['type'],
            },
        ),
        migrations.CreateModel(
            name='CommonFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('release_date', models.DateTimeField()),
                ('poster_image', models.ImageField(upload_to='photos%y%m%d')),
                ('actors', models.ManyToManyField(to='pinterest.Casts')),
                ('categories', models.ManyToManyField(to='pinterest.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('commonfeatures_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pinterest.commonfeatures')),
                ('running_time', models.IntegerField()),
            ],
            bases=('pinterest.commonfeatures',),
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('commonfeatures_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pinterest.commonfeatures')),
                ('episodes_num', models.IntegerField()),
            ],
            bases=('pinterest.commonfeatures',),
        ),
    ]
